language: java

addons:
  sonarcloud:
    organization: "bryanbenavente"
      token:
        secure: a3366967912af64dcfbee324a8d7aecff12e01b1

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=BryanBenavente_demo-travis